# Generated by Django 2.1.4 on 2018-12-30 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_simple_gallery', '0004_gallarypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallarypage',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Show images in this collection in the gallery view.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_simple_gallery.SimpleGalleryIndex', verbose_name='Collection'),
        ),
    ]
