# Generated by Django 2.1.4 on 2018-12-26 11:23

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181226_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCat2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'BlogCat2',
                'verbose_name_plural': 'Categories_tow',
            },
        ),
        migrations.AddField(
            model_name='postpage',
            name='categories_two',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.BlogCat2'),
        ),
    ]
