# Generated by Django 2.1.4 on 2018-12-29 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0007_auto_20181228_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='header_image',
            field=models.ForeignKey(blank=True, help_text='A big banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
