# Generated by Django 2.1.4 on 2018-12-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogcategory_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='header_image',
        ),
    ]
