# Generated by Django 2.1.4 on 2018-12-29 07:02

from django.db import migrations, models
import django.db.models.deletion
import home.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181228_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='custom_editor',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='A big banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='streamfiled',
            field=wagtail.core.fields.StreamField([('qoute', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(max_length=500, required=True)), ('author', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('link', wagtail.core.blocks.URLBlock(required=True))], help_text='A block for uplifting external source.')), ('paragraph', home.models.ParagraphBlock('Paragraph help text'))], blank=True),
        ),
    ]
