# Generated by Django 2.1.4 on 2018-12-29 11:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('post_to_medium', models.BooleanField(blank=True, null=True)),
                ('post_to_twitter', models.BooleanField(blank=True, null=True)),
                ('post_to_facebook', models.BooleanField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('date_override', models.DateField(blank=True, verbose_name='Published date override')),
                ('post_content', wagtail.core.fields.RichTextField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
