# Generated by Django 2.1.4 on 2018-12-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='post_to_facebook',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='post_to_medium',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='post_to_twitter',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
